server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/users

        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
    config:
      import: "optional:configserver:http://config-server:8888"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/